name: Acquire activation file
on: [push]
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
      # Request manual activation file
      - name: Unity - Request Activation File
        uses: game-ci/unity-request-activation-file@v2.0-alpha-1
        id: getManualLicenseFile
        with: 
          unityVersion: 2019.4.21f1
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.getManualLicenseFile.outputs.filePath }}
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
