name: Build and deploy WebGL

on:
  push:
    branches: [main]

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
 
jobs:
  buildWEBG:
    name: Build and deploy WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v2.1.4
        with:
          path: Cyberbug-2021/Library
          key: Library-Cyberbug-2021-WebGL
          restore-keys: |
            Library-Cyberbug-2021-
            Library-

      # Build
      - name: Build for WebGL
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: './Cyberbug-2021'
          unityVersion: 2019.4.21f1
          targetPlatform: WebGL
          #allowDirtyBuild: true
          
      # Deploy to Github Pages
      - name : Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/WebGL/WebGL # The folder the action should deploy.
          
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v2.1.4
        with:
          path: Cyberbug-2021/Library
          key: Library-Cyberbug-2021-Windows
          restore-keys: |
            Library-Cyberbug-2021-
            Library-

      # Build
      - name: Build for Windows
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: './Cyberbug-2021'
          unityVersion: 2019.4.21f1
          targetPlatform: StandaloneWindows64
          #allowDirtyBuild: true

      # Output
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      
